load('data63.mat');
n=length(C);
m=0;
A1 = randi([1,10],m,n);
s=35;
x0=s/n*ones(n,1);
A = double.empty(0,n);
b = double.empty(0,1);
[xind, ~] = heur(C,s,A,b);
x=zeros(n,1);
x(xind)=1;
b1 = A1*x-ones(m,1);
Prob = MESP(C,A1,b1);
gamma=Prob.BFGS_Linx_gamma(s);

C=Prob.C;
C_comp=Prob.C_comp;
size=Prob.size;
r=Prob.r;
A=Prob.A;
b=Prob.b;
F=Prob.F;
Fsquare=Prob.Fsquare;
F_comp=Prob.F_comp;
Fsquare_comp=Prob.Fsquare;
ldetC=Prob.ldetC;
scaleC=Prob.scaleC;
